name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout your repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Install Node.js and dependencies
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      # Build the project
      - name: Build project
        run: npm run build

      # Deploy the dist folder to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
